package com.rest.example.demo.util;

public enum SupportedQueryPattern {
	STATUS, FLIGHTNUMBER, DEPARTURE_AND_ARRIVAL, STATUS_AND_DEPARTURE_AND_ARRIVAL, STATUS_AND_DEPARTURE_OR_ARRIVAL, NOT_SUPPORTED, ALL, DEPARTURE, ARRIVAL, STATUS_AND_DEPARTURE, STATUS_AND_ARRIVAL;

}
